### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by xbh03** [mimooh/ovclient#1]
Hello @mimooh this script is fantastic, because it's perfect for me, I need to create more ovpn clients, but I can't to do that manually in the classic "openvpn-install.sh" interactive script, so I'm integrating Woocommerce with Make.com to my SSH server to execute a simple command with args "./script -a $customer_id", but that doesn't work.

In your script you inserted  this directory " /etc/openvpn/server/" but seems that it's incorrect in my case, I'm using the classic "openvpn-install.sh", can you send me some information or instruction about the use of your script? Thanks.

I would like to execute with the classic "./openvpn-install.sh 1 $customer_id 1" but I can't.... 
![image](https://user-images.githubusercontent.com/48808488/198414964-2fd0f39b-3a12-48b6-ba9a-921aa94e32ab.png)

**Comment by mimooh** [comment]
Hi! what is your equivivalent for ubuntu's /etc/openvpn/server/? This
should be a part of your open VPN installation.

pt., 28 paź 2022, 01:14 użytkownik Francesco Zoino ***@***.***>
napisał:

**Comment by xbh03** [comment]
![putty_bwKPMretu3](https://user-images.githubusercontent.com/48808488/198565946-948fc233-8e6f-4bf0-a675-281438a04760.png)
Oh yes, is it, but why doesn't work?

**Comment by xbh03** [comment]
![image](https://user-images.githubusercontent.com/48808488/198568535-f05b2fd8-b196-42a9-99bc-5a26a682866e.png)
The interesting function is that your script create a directory, but show some errors... And the file OVPN doesn't work

**Comment by xbh03** [comment]
![image](https://user-images.githubusercontent.com/48808488/198568690-c26127e9-30f1-49aa-877c-50231b7086bb.png)

**Comment by mimooh** [comment]
First I am sorry for not making clear, that you need to install server installer first - I alread updated the project info:

ovclient.sh is a client for https://github.com/Nyr/openvpn-install (an easy and interactive openvpn SERVER installer) -- you must first install that and only then use ovclient.sh

Second, I noticed that there was another issue: the client would ask for "yes/no" (likely a change in easyrsa software) - I fixed that too. Works for me in ubuntu with no issues.

**Comment by mimooh** [comment]
If it still won't work for you, we can meet online and share desktops to fix things out since I don't want to provide crap software to community :)

**Comment by xbh03** [comment]
I modified some paths in your script, now working correctly!

**Comment by mimooh** [comment]
Perhaps there's something I should change in my script?

Karol Kreński
tel. 517-302-055

**Comment by xbh03** [comment]
I removed "/server/" word in the paths, also I seen that your script create only keys (related to openvpn error) so I added via another script some settings of my server.

Also, automated successfully all with make.com
